---

- name: postfix restart
  service: name=postfix state=restarted
  notify: postfix send test mail
  ignore_errors: yes

- name: postfix opendkim restart
  service: name=opendkim state=restarted
  notify: postfix send test mail
  ignore_errors: yes

- name: saslauthd restart
  service: name=saslauthd state=restarted
  ignore_errors: yes

- name: spamassassin restart
  service: name=spamassassin state=restarted
  ignore_errors: yes

- name: "postfix send test mail"
  shell: echo "Test mail from new/updated postfix at" `hostname` | mail {{postfix_send_test_mail_to}} -s "Test SMTP `hostname`"
  when: postfix_send_test_mail_to != ""
  ignore_errors: yes
