---

- name: Install requirements (Debian)
  apt: name={{item}}
  with_items:
  - postfix
  - ca-certificates
  - mailutils
  - spamassassin
  - spamc

- name: Install sasl requirements (Debian)
  apt: name={{item}}
  with_items:
  - libsasl2-2
  - sasl2-bin
  - libsasl2-modules
  when: postfix_smtpd_auth_sasl_enable is defined

- name: Install DKIM requirements (Debian)
  apt: name={{item}}
  when: postfix_dkim
  with_items:
  - opendkim
  - opendkim-tools

- name: Install postfix-pcre
  apt: pkg=postfix-pcre
  when: postfix_rewrite_sender_address != ""
