---

- name: Install requirements (RedHat)
  yum: name={{item}}
  with_items:
  - postfix
  - ca-certificates
  - mailx
  - spamassassin

- name: Install DKIM requirements (RedHat)
  yum: name=opendkim
  when: postfix_dkim
