terms:
  - id: http://creativecommons.org/publicdomain/zero/1.0/
    term: Creative Commons Zero
    active: true
  - id: http://creativecommons.org/licenses/by/4.0/
    term: Creative Commons Attribution
    active: true
  - id: http://creativecommons.org/licenses/by-sa/4.0/
    term: Creative Commons Attribution - Share Alike
    active: true
  - id: http://creativecommons.org/licenses/by-nd/4.0/
    term: Creative Commons Attribution - No Derivatives
    active: true
  - id: http://creativecommons.org/licenses/by-nc/4.0/
    term: Creative Commons Attribution - Noncommercial
    active: true
  - id: http://creativecommons.org/licenses/by-nc-sa/4.0/
    term: Creative Commons Attribution - Noncommercial - Sare Alike
    active: true
  - id: http://creativecommons.org/licenses/by-nc-nd/4.0/
    term: Creative Commons Attribution
    active: true
  - id: http://www.apache.org/licenses/LICENSE-2.0
    term: Apache License
    active: true
  - id: https://opensource.org/licenses/BSD-3-Clause
    term: The 3-Clause BSD License
    active: true
  - id: https://opensource.org/licenses/MIT
    term: The MIT License
    active: true
  - id: https://www.gnu.org/licenses/gpl-3.0.txt
    term: GNU General Public License
    active: true
