:terms:
    - :id: http://libraries.ucsd.edu/about/digital-library/
      :term: Digital Library Development Program, UC San Diego, La Jolla, 92093-0175 (http://libraries.ucsd.edu/about/digital-library/)
    - :id: http://libraries.ucsd.edu/services/data-curation/
      :term: Research Data Curation Program, UC San Diego, La Jolla, 92093-0175 (http://libraries.ucsd.edu/services/data-curation/)
    - :id: http://libraries.ucsd.edu/collections/sca/
      :term: Special Collections & Archives, UC San Diego, La Jolla, 92093-0175 (http://libraries.ucsd.edu/collections/sca/)

