terms:
  - id: http://id.loc.gov/vocabulary/resourceTypes/car
    term: Cartographic
  - id: http://id.loc.gov/vocabulary/resourceTypes/dat
    term: Data
  - id: http://id.loc.gov/vocabulary/resourceTypes/mix
    term: Mixed material
  - id: http://id.loc.gov/vocabulary/resourceTypes/mov
    term: Moving image
  - id: http://id.loc.gov/vocabulary/resourceTypes/mul
    term: Multimedia
  - id: http://id.loc.gov/vocabulary/resourceTypes/nmv
    term: Notated movement
  - id: http://id.loc.gov/vocabulary/resourceTypes/not
    term: Notated music
  - id: http://id.loc.gov/vocabulary/resourceTypes/sof
    term: Software
  - id: http://id.loc.gov/vocabulary/resourceTypes/aud
    term: Sound recording
  - id: http://id.loc.gov/vocabulary/resourceTypes/aum
    term: Sound recording-musical
  - id: http://id.loc.gov/vocabulary/resourceTypes/aun
    term: Sound recording-nonmusical
  - id: http://id.loc.gov/vocabulary/resourceTypes/img
    term: Still image
  - id: http://id.loc.gov/vocabulary/resourceTypes/txt
    term: Text
  - id: http://id.loc.gov/vocabulary/resourceTypes/art
    term: Three dimensional object
