---
#- name: Server Level Config
#  hosts: "horton_fedora:horton_solr:horton_samvera:horton_sidekiq:horton_sidekiq_master"
#  strategy: debug
#  roles:
#    - { role: geerlingguy.repo-epel }
#    - { role: packages }
#    - { role: system_setup }
#    - { role: repleo.postfix }
##T    - { role: dj-wasabi.ossec-server }
##T    - { role: notch8.swap, tags: 'swap' }
##T    - { role: notch8.site24x7, tags: 'monitoring' }
#    - { role: notch8.ssh, tags: 'permissions' }
##    - { role: nbigot.fail2ban, tags: 'fail2ban' }
## TODO ssh config customization

- name: Rails Config
  hosts: "horton_samvera:horton_sidekiq:horton_sidekiq_master"
  strategy: debug
  roles:
#    - { role: notch8.ffmpeg }
    - { role: geerlingguy.nodejs }
    - { role: rvm_io.ruby, tags: ruby }
    - { role: hydra-stack/config-deploy }
    - { role: sufia_dependencies/install }
    - { role: sufia_dependencies/config }

- name: Fedora Config
  hosts: "horton_fedora"
#  strategy: debug
  roles:
    - { role: hydra-stack/fedora }
# TODO log rotate

- name: Solr Config
  hosts: "horton_solr"
#  strategy: debug
  roles:
    - { role: AnsibleShipyard.ansible-zookeeper }
    - { role: hydra-stack/solr }
# TODO log rotate

- name: Rails Config
  hosts: "horton_samvera:horton_sidekiq:horton_sidekiq_master"
  roles:
#    - { role: jcid.ffmpeg }
    - { role: notch8.ffmpeg }
    - { role: geerlingguy.nodejs }
    - { role: rvm_io.ruby, tags: ruby }
    - { role: hydra-stack/config-deploy }
    - { role: sufia_dependencies/install }
    - { role: sufia_dependencies/config }

- name: Samvera Config
  hosts: "horton_samvera"
#  strategy: debug
  roles:
    - { role: webserver/install }
    - { role: webserver/config }

# TODO log rotate
- name: Sidekiq Config Master
  hosts: "horton_sidekiq_master"
  roles:
    - { role: DavidWittman.redis }
    - { role: sidekiq }

- name: Sidekiq Config Slave
  hosts: "horton_sidekiq"
  vars:
    redis_slaveof: "{{ hostvars['horton_sidekiq_master'].ansible_eth1.ipv4.address }} {{ redis_port }}"
  roles:
    - { role: DavidWittman.redis }
    - { role: sidekiq }

- name: HA Proxy Web
  hosts: "horton_ha_proxy_web"
  roles:
    - { role: openmicroscopy.haproxy }

- name: HA Proxy Fedora / Solr
  hosts: "horton_ha_proxy_fedora"
  gather_facts: true
  roles:
    - { role: openmicroscopy.haproxy }

- include: deploy.yml
