---
- name: Bring up docker containers
  hosts: localhost
  gather_facts: false
  environment:
    POSTGRES_PASSWORD: "{{ hydra_db_pass }}"
  tasks:
    - docker_service:
        project_name: horton
        project_src: .
        scale:
          fedora: 2
          solr: 1
          samvera: 1
          sidekiq: 1
          sidekiq_master: 1
          ha_proxy_web: 1
          ha_proxy_fedora: 1
      register: output
    - meta: refresh_inventory

- name: Fix sudoers
  hosts: "horton_fedora:horton_solr:horton_samvera:horton_ha_proxy_web:horton_ha_proxy_fedora:horton_sidekiq:horton_sidekiq_master"
  roles:
    - sudoersfix

- include: configure.yml 

