- name: Rollback Rails App
  hosts: "horton_samvera:horton_sidekiq:horton_sidekiq_master"
  become_user: "{{ capistrano_user }}"
  become: yes
  roles:
    - { role: carlosbuenosvinos.ansistrano-rollback }
